#!/usr/bin/python
import pprint
import sys
import glob


import xml.dom.minidom
from xml.dom.minidom import Node
 
wordlist = []

outfile = open("combo_lock_word_list.txt", "w");

column1 = "WADEGHLMRS"
column2 = "RTUAEILNOP"
column3 = "ORSTUAEILN"
column4 = "KLNRSTACDE"
column5 = " HKRSTYADE"  # replaced '_' with space to make word lookups easier

dfile1 = open("mwords/354984si.ngl")
dlist1 = dfile1.readlines()
dlist1 = [ x.strip() for x in dlist1 ]
dset1 = set(dlist1)


dfile2 = open("mwords/256772co.mpo")
dlist2 = dfile2.readlines()
dlist2 = [ x.strip() for x in dlist2 ]
dset2 = set(dlist2)

dbigset = dset1 | dset2
#print dbigset

wordlist = []
wordset = set([])
for col1 in column1:
  for col2 in column2:
    for col3 in column3:
      for col4 in column4:
        for col5 in column5:
          wordstr = col1+col2+col3+col4+col5
          wordstr = wordstr.lower()
          wordstr = wordstr.strip()
          wordset.add(wordstr)
          wordlist.append(wordstr)

realwordset = wordset &  dbigset

realwordlist = list(realwordset)

realwordlist.sort()

for ele in realwordlist:
  outfile.write(ele + '\n')

outfile.close()
