#!/usr/bin/python

# Print gpx waypoints in a format that is nice for geocache submission

import sys
import latlong_in_decimal_minutes as ll

from bs4 import BeautifulSoup

def handle_xml_file(xmlfile):
        file=open(xmlfile, 'r')
        soup = BeautifulSoup(file, "lxml")
        print ("===================== " + xmlfile + " =============================")
        for wpt in soup.find_all('wpt'):
                print('  ' + wpt.find("name").string + ':')
                if(wpt.find("cmt")):
                        print('\t' + wpt.find("cmt").string)
                print('\t' + wpt.time.string)
                ll.printf('\t')
                ll.latlong_in_decimal_minutes(wpt['lat'],wpt['lon'])
                print('')


for file in sys.argv[1:]:
        handle_xml_file(file)



