#!/usr/bin/python

# Print gpx waypoints in a format that is nice for geocache submission

import sys
import latlong_in_decimal_minutes as ll

from bs4 import BeautifulSoup

def handle_xml_file(xmlfile):
        file=open(xmlfile, 'r')
        cnt = 0
        soup = BeautifulSoup(file, "lxml")
        print ("===================== " + xmlfile + " =============================")
        for wpt in soup.find_all('wpt'):
                cnt += 1
                print("\t\t\t\t # " + str(cnt))
                if(wpt.find("name")):
                        print(wpt.find("name").string + ':')
                if(wpt.find("cmt")):
                        print(wpt.find("cmt").string)
                if(wpt.find("time")):
                        print(wpt.find("time").string)
                ll.latlong_in_decimal_minutes(wpt['lat'],wpt['lon'])
                print('---------------------------------------------------------------')


for file in sys.argv[1:]:
        handle_xml_file(file)



